alerts/urls.py
from django.urls import path

from . import views

app_name = 'alerts'

urlpatterns = [
    path("", views.Index.as_view(),
         name="index_url"),
    path("account/", views.Account.as_view(),
         name="account_url"),
    path("alerts/create/", views.AlertCreate.as_view(),
         name="alert_create"),
    path("alerts/<int:id>/", views.AlertsPage.as_view(),
         name="alert_page_url"),
    path("alerts/<int:id>/edit/", views.EditAlert.as_view(),
         name="alert_edit_url"),
    path("alerts/<int:pk>/delete/", views.DeleteAlert.as_view(),
         name="alert_delete_url"),
    path("alerts/", views.AlertsPage.as_view(),
         name="alerts_page_url"),
    path('alerts/<int:id>/active/', views.change_task_status,
         name="alerts_status_url"),
    path("<username>/", views.Profile.as_view(),
         name="profile_url"),
]

api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

from .views import RegisterApi

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('signup/', RegisterApi.as_view(), name='signup'),

]

django_alerts/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("auth/", include("users.urls")),
    path("", include("alerts.urls")),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
]

users/urls.py
from django.urls import include, path

from . import views

app_name = 'users'

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

alerts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class AlertTask(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user")
    header = models.CharField(max_length=150)
    description = models.CharField(max_length=150)
    location = models.CharField(max_length=150)
    date_created = models.DateTimeField(auto_now=True)
    date_expire = models.DateTimeField()

    def __str__(self):
        return self.header


class Participant(models.Model):
    participant = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="participant_participant")
    task = models.ForeignKey(AlertTask, on_delete=models.CASCADE,
                             related_name="participant_task")
    task_active = models.BooleanField(default=True)

alerts/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget

from .models import AlertTask, User


class AlertTaskForm(forms.ModelForm):

    participants = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple, )

    class Meta:
        model = AlertTask
        fields = ('header', 'description', 'location', 'date_expire',)
        widgets = {
            "date_expire": SelectDateWidget(),
            'description': forms.Textarea(attrs={
                'class': 'form-control', 'rows': 6
            }),
        }

alerts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View

from .forms import AlertTaskForm
from .mixins import ObjectMixin
from .models import AlertTask, Participant
from .utils import get_partisipants_list, get_users


class Index(ObjectMixin, View):
    """Представление главной страницы."""
    template = 'index.html'


class Profile(ObjectMixin, View):
    """Представление страницы профиля пользователя."""
    template = 'profile.html'


class Account(LoginRequiredMixin, ObjectMixin, View):
    """Представление страницы личного кабинета."""
    template = 'account.html'


def get(request):
    form = AlertTaskForm()
    return render(request, 'form_alert.html', context={'form': form})


class AlertCreate(LoginRequiredMixin, View):
    """Представление страницы создания напоминания."""

    def get(self, request):
        form = AlertTaskForm()
        return render(request, 'form_alert.html', context={'form': form})

    def post(self, request):
        form = AlertTaskForm(request.POST)
        if form.is_valid():
            new = form.save(commit=False)
            new.author_id = request.user.id
            new.save()

            users_list = get_users(request, request.user.id)
            print(users_list, type(users_list))
            participant_list = [Participant(
                participant=user, task=new) for user in users_list]
            Participant.objects.bulk_create(participant_list)

            return redirect('alerts:account_url')

        return redirect('alerts:account_url')


class AlertsPage(LoginRequiredMixin, View):
    """Представление для страницы с напоминаниями в личном кабинете."""

    def get(self, request, id=None):
        if id is None:
            my_alerts = AlertTask.objects.filter(author=request.user)
            try:
                invited_me_alerts = AlertTask.objects.filter(
                    participant_task__participant=request.user).\
                    exclude(author=request.user)

                return render(request, 'alerts.html', context={
                    'my_alerts': my_alerts,
                    "invited_me_alerts": invited_me_alerts,
                })
            except Exception:

                return render(request, 'alerts.html', context={
                    'my_alerts': my_alerts, })
        else:
            alert = get_object_or_404(AlertTask, id=id)
            participants = Participant.objects.filter(task=id)
            user_active_status = get_object_or_404(
                Participant, participant=request.user, task=id)

            return render(request, 'single_alert.html', context={
                'alert': alert, 'participants': participants,
                'user_active_status': user_active_status,
            })


class EditAlert(LoginRequiredMixin, View):
    """Представление формы редактирования напоминания."""

    def get(self, request, id):
        alert = get_object_or_404(AlertTask, author=request.user, id=id)
        if request.user != alert.author:
            return redirect('alerts:alerts_page_url')

        form = AlertTaskForm(instance=alert)
        participants_list = get_partisipants_list(id)
        return render(request, 'form_alert.html', context={
            'form': form,
            'alert': alert,
            'participants_list': participants_list,
        })

    def post(self, request, id):
        alert = get_object_or_404(AlertTask, author=request.user, id=id)
        if request.user != alert.author:
            return redirect('alerts:alerts_page_url')

        form = AlertTaskForm(request.POST, instance=alert)

        if form.is_valid():
            users_list = get_users(request)
            participant_list = [user for user in users_list]
            for user in participant_list:
                Participant.objects.update_or_create(
                    participant=user, task=alert)
            form.save()
        else:
            return render(request, 'form_alert.html', context={
                'form': form,
                'alert': alert
            })

        return redirect('alerts:alerts_page_url')


class DeleteAlert(LoginRequiredMixin, View):
    """Представление формы удаления напоминания."""

    def post(self, request, pk):
        alert = get_object_or_404(AlertTask, id=pk)
        if request.method == 'POST' and request.user == alert.author:
            alert.delete()
        else:
            return redirect('alerts:alerts_page_url')
        return render(request, 'account.html')


def change_task_status(request, id):
    """
    Изменяет статус конкретного оповещения через кнопку на странице оповещения.
    Простое решение без JS.
    """

    status = get_object_or_404(Participant, task=id, participant=request.user)
    if request.GET.get('status_button'):
        status.task_active = False
    else:
        status.task_active = True
    return render(request, 'account.html')

templates/account.html
{% extends "base.html" %} 
{% block title %} Мой кабинет {% endblock %}
{% load user_filters %}
{% load static %}
{% block content %}

<div class="main__header">
    <h1 class="main__title">Личный кабинет</h1>
    
</div>
<div>
    <a href="{% url 'alerts:alert_create' %}"><button type="button" class="btn btn-primary">Создать оповещение</button></a>
        <a href="{% url 'alerts:alerts_page_url' %}"><button type="button" class="btn btn-secondary">Список оповещений</button></a>

{% endblock %}

templates/alerts.html
{% extends "base.html" %} 
{% block title %} Управление напоминаниями {% endblock %}
{% load user_filters %}
{% load static %}
{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Сервис e-mail-оповещений</h1>
    Мои напоминания:

    
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Автор</th>
          <th scope="col">Заголовок</th>
          <th scope="col">Место</th>
          <th scope="col">Дата и время</th>
        </tr>
      </thead>
      <tbody>
        {% for alert in my_alerts %}
        <tr>
          <th scope="row"><a href="{% url 'alerts:profile_url' alert.author %}">{{ alert.author }}</a></th>
          <td> <a href="{% url 'alerts:alert_page_url' alert.id %}"> {{ alert.header }} </a></td>
          <td>{{ alert.location }}</td>
          <td>{{ alert.date_expire }}</td>
         
        </tr>
    {% endfor %}
      </tbody>
    </table>
   
 
 

 <div>   Меня пригласили в:
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Автор</th>
        <th scope="col">Заголовок</th>
        <th scope="col">Место</th>
        <th scope="col">Дата и время</th>
      </tr>
    </thead>
    <tbody>
      
      {% for alert in invited_me_alerts %}
      <tr>
        <th scope="row"><a href="{% url 'alerts:profile_url' alert.author %}">{{ alert.author }}</a></th>
        <td> <a href="{% url 'alerts:alert_page_url' alert.id %}"> {{ alert.header }} </a></td>
        <td>{{ alert.location }}</td>
        <td>{{ alert.date_expire }}</td>
   
      </tr>
  {% endfor %}
    </tbody>
  </table>
   
    

</div>
</div>

</main>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="body">
    <header class="header">
    </header>
    <main class="main container">
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>

templates/form_alert.html
{% extends "base.html" %} 
{% block title %} Мой кабинет {% endblock %}
{% load user_filters %}
{% load static %}
{% block content %}

<div class="main__header">
    <h1 class="main__title">Поставить напоминание</h1>
    
</div>
<div>
    <form class="form" method="post" enctype="multipart/form-data" action="."> 
        {% csrf_token %}
        <div class="form__group">
            <label for="id_name" class="form__label">Заголовок</label>
            <div class="form__field-group">
                {{ form.header|addclass:"form__input" }}
                {% if form.errors %}
                    {% for error in form.header.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
       
        <div class="form__group">
            <label for="id_name" class="form__label">Описание</label>
            <div class="form__field-group">
                {{ form.description|addclass:"form__input" }}
                {% if form.errors %}
                    {% for error in form.description.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__group">
            <label for="id_time" class="form__label">Место</label>
            <div class="form__field-group form__field-group_time">
                {{ form.location|addclass:"form__input" }}
            
                {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.date_expire.id_for_label }}" class="form__label">Дата</label>
            <div class="form__field-group">
                {{ form.date_expire|addclass:"form__textarea" }}
                {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        <div class="form__group">
            <label for="{{ form.participants.id_for_label }}" class="form__label">Добавить участников</label>
            <div class="form__field-group">
            {% if participants_list %}
                (Уже приглашены:
              {% for user in participants_list %}
              {{ user.participant.username }}
              {% endfor %})
                {% endif %}
              {{ form.participants }}
              
                {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form__footer">
            {% if 'create' in request.path %}
            <button class="button button_style_blue" type="submit" id="submit-button">Создать напоминание</button>
          {% else %}
            <button class="button button_style_blue" type="submit" id="submit-button">Изменить напоминание</button>

          {% endif %}
        </div>
    </form>
    <form action="{% url 'alerts:alert_delete_url' alert.pk %}" method="POST">
                {% csrf_token %}
                <button class="button button_style_blue" type="submit" >Удалить </button>
            </form>
</div>
</main>

{% endblock %}

templates/index.html
{% extends "base.html" %} 
{% block title %} Сервис e-mail-оповещений {% endblock %}
{% load user_filters %}
{% load static %}
{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Сервис e-mail-оповещений</h1>
    {% if request.user.is_authenticated %} <a href="{% url 'alerts:account_url' %}"><button type="button" class="btn btn-primary">Кабинет</button></a>
    <a href="{% url 'users:logout' %}"><button type="button" class="btn btn-primary">Выйти</button></a>
    {% else %}<a href="{% url 'users:signup' %}"><button type="button" class="btn btn-secondary">Регистрация</button></a>
    <a href="{% url 'users:login' %}"><button type="button" class="btn btn-primary">Войти</button></a>{% endif %}
</div>

</main>
{% endblock %}

templates/profile.html
{% extends "base.html" %} 
{% block title %} Пользователь {{ obj.username }}{% endblock %}
{% load user_filters %}
{% load static %}
{% block style %} <link rel="stylesheet" href={% static "/pages/index.css" %}>{% endblock %}
{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">{{ obj.username }}</h1>
    <h1 class="main__title">{{ obj.first_name }}</h1>


    <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"> </th>
          </tr>
        </thead>
        <tbody>
      
          <tr>
            <th scope="row">{{ obj.username }}</a></th>
            <td> {{ obj.first_name }} </a></td>
            <td>{{ obj.last_name }}</td>
            <td>{{ obj.email }}</td>
          </tr>

        </tbody>
      </table>
    
</div>

    
</div>

</main>
{% endblock %}

templates/single_alert.html
{% extends "base.html" %} 
{% block title %} Просмотр упоминания {% endblock %}
{% load user_filters %}
{% load static %}
{% block style %}<link rel="stylesheet" href={% static "/pages/index.css" %}>{% endblock %}
{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Сервис e-mail-оповещений</h1>


    <table class="table">
        <thead>
          <tr>
            <th scope="col">Автор</th>
            <th scope="col">Заголовок</th>
            <th scope="col">Место</th>
            <th scope="col">Описание</th>
            <th scope="col">Дата и время</th>
            <th scope="col">Статус</th>
            <th scope="col">Участники</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">{{ alert.author }}</th>
            <td>{{ alert.header }}</td>
            <td>{{ alert.location }}</td>
            <td>{{ alert.description }}</td>
            <td>{{ alert.date_expire }}</td>
            <td><form action="{% url 'alerts:alerts_status_url' alert.id %}" method='GET'>
              {% csrf_token %}
              {% if user_active_status.task_active %}
              <button class="button button_style_blue" type="submit" id="off-button" name="status_button" value="False">Отключить</button>
              {% else %}
              <button class="button button_style_red" type="submit" id="on-button" name="status_button" value="True">Включить</button>
              {% endif %}
            </form>
            </td>
            <td>{% for i in participants %}{{ i.participant }} {% endfor %}</td>
          </tr>
         
        </tbody>
      </table>
 
   {% if request.user == alert.author %}<li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'alerts:alert_edit_url' alert.id %}" class="single-card__text">Редактировать</a></li>{% endif %}

</div>
</div>

</main>
{% endblock %}